micronaut:
  banner:
    enabled: false
  application:
    name: rabbitpoc
  security:
    authentication: idtoken
    oauth2:
      clients:
        default:
          client-secret: ${OAUTH_CLIENT_SECRET:YYY}
          client-id: ${OAUTH_CLIENT_ID:postman}
          openid:
            issuer: ${OAUTH_ISSUER:`https://keycloak.glubo.cz/realms/glubot`}
      enabled: true
    intercept-url-map:
      - pattern: /static/*
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /oauth/*
        access:
          - isAnonymous()
      - pattern: /health
        access:
          - isAnonymous()
    endpoints:
      login:
        enabled: true
      logout:
        get-allowed: true
  views:
    jte:
      dynamic: false
      binary-static-content: true
  router:
    static-resources:
      favicon:
        enabled: true
        mapping: "/**"
        paths: classpath:static
      default:
        enabled: true
        mapping: "/static/**"
        paths: classpath:static
logger:
  levels:
    ROOT: INFO
#    io.micronaut.security: DEBUG
